version: "3.9"

services:
  web:
    image: silexa/app-ReleaseParty-web:local
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "${APP_WEB_PORT:-3000}:3000"
    secrets:
      - source: app_env
        target: app_env
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  backend:
    image: silexa/app-ReleaseParty-backend:local
    environment:
      NODE_ENV: production
      PORT: 8080
    ports:
      - "${APP_BACKEND_PORT:-8080}:8080"
    secrets:
      - source: app_env
        target: app_env
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

secrets:
  app_env:
    external: true
    name: app-ReleaseParty-env

networks:
  default:
    external: true
    name: ${SILEXA_NETWORK:-silexa_net}
