package stripebridge

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
)

type mockEventLogger struct {
	events []map[string]any
}

func (m *mockEventLogger) Log(event map[string]any) {
	copyEvent := map[string]any{}
	for key, value := range event {
		copyEvent[key] = value
	}
	m.events = append(m.events, copyEvent)
}

func TestClientDoGETBuildsQuery(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if got := r.Method; got != http.MethodGet {
			t.Fatalf("unexpected method: %s", got)
		}
		if got := r.URL.Path; got != "/v1/products" {
			t.Fatalf("unexpected path: %s", got)
		}
		if got := r.URL.Query().Get("limit"); got != "3" {
			t.Fatalf("unexpected limit query: %q", got)
		}
		if got := r.URL.Query().Get("active"); got != "true" {
			t.Fatalf("unexpected active query: %q", got)
		}
		if got := r.Header.Get("Authorization"); got != "Bearer sk_test_123" {
			t.Fatalf("unexpected auth header: %q", got)
		}
		_, _ = w.Write([]byte(`{"object":"list","data":[],"has_more":false}`))
	}))
	defer srv.Close()

	client, err := NewClient(ClientConfig{
		APIKey:     "sk_test_123",
		BaseURL:    srv.URL,
		HTTPClient: srv.Client(),
	})
	if err != nil {
		t.Fatalf("new client: %v", err)
	}
	resp, err := client.Do(context.Background(), Request{
		Method: "GET",
		Path:   "/v1/products",
		Params: map[string]string{"limit": "3", "active": "true"},
	})
	if err != nil {
		t.Fatalf("client do: %v", err)
	}
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("unexpected status: %d", resp.StatusCode)
	}
}

func TestBuildRequestContentForPostForm(t *testing.T) {
	content, path, err := buildRequestContent("/v1/products", "POST", map[string]string{"name": "Demo"}, "")
	if err != nil {
		t.Fatalf("build content: %v", err)
	}
	if path != "/v1/products" {
		t.Fatalf("unexpected path %q", path)
	}
	if content == "" || !strings.Contains(content, "name=Demo") {
		t.Fatalf("expected encoded form content, got %q", content)
	}
}

func TestClientDoWritesLogEvents(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		_, _ = w.Write([]byte(`{"id":"prod_1"}`))
	}))
	defer srv.Close()

	logger := &mockEventLogger{}
	client, err := NewClient(ClientConfig{
		APIKey:     "sk_test_123",
		BaseURL:    srv.URL,
		HTTPClient: srv.Client(),
		Logger:     logger,
		LogContext: map[string]string{"environment": "sandbox"},
	})
	if err != nil {
		t.Fatalf("new client: %v", err)
	}
	_, err = client.Do(context.Background(), Request{
		Method: "GET",
		Path:   "/v1/products/prod_1",
	})
	if err != nil {
		t.Fatalf("client do: %v", err)
	}
	if len(logger.events) < 2 {
		t.Fatalf("expected at least request+response events, got %d", len(logger.events))
	}
	if logger.events[0]["event"] != "request" {
		t.Fatalf("unexpected first event: %+v", logger.events[0])
	}
}

func TestClientDoAutogeneratesIdempotencyForPost(t *testing.T) {
	capturedIdempotency := ""
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedIdempotency = strings.TrimSpace(r.Header.Get("Idempotency-Key"))
		_, _ = w.Write([]byte(`{"id":"prod_1"}`))
	}))
	defer srv.Close()

	logger := &mockEventLogger{}
	client, err := NewClient(ClientConfig{
		APIKey:     "sk_test_123",
		BaseURL:    srv.URL,
		HTTPClient: srv.Client(),
		Logger:     logger,
	})
	if err != nil {
		t.Fatalf("new client: %v", err)
	}
	_, err = client.Do(context.Background(), Request{
		Method: "POST",
		Path:   "/v1/products",
		Params: map[string]string{"name": "Demo"},
	})
	if err != nil {
		t.Fatalf("client do: %v", err)
	}
	if strings.TrimSpace(capturedIdempotency) == "" {
		t.Fatalf("expected autogenerated idempotency header")
	}
	if len(logger.events) == 0 {
		t.Fatalf("expected request log event")
	}
	requestEvent := logger.events[0]
	key, _ := requestEvent["idempotency_key"].(string)
	if strings.TrimSpace(key) == "" || strings.TrimSpace(key) == "-" {
		t.Fatalf("expected autogenerated idempotency key in request event: %+v", requestEvent)
	}
	auto, _ := requestEvent["idempotency_auto"].(bool)
	if !auto {
		t.Fatalf("expected idempotency_auto=true: %+v", requestEvent)
	}
}

func TestClientDoNormalizesHTTPError(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Request-Id", "req_123")
		w.WriteHeader(http.StatusBadRequest)
		_, _ = w.Write([]byte(`{"error":{"type":"invalid_request_error","code":"resource_missing","param":"id","message":"No such product","doc_url":"https://docs.stripe.com/errors"}}`))
	}))
	defer srv.Close()

	client, err := NewClient(ClientConfig{
		APIKey:     "sk_test_123",
		BaseURL:    srv.URL,
		HTTPClient: srv.Client(),
	})
	if err != nil {
		t.Fatalf("new client: %v", err)
	}
	_, err = client.Do(context.Background(), Request{
		Method: "GET",
		Path:   "/v1/products/prod_missing",
	})
	if err == nil {
		t.Fatalf("expected error")
	}
	apiErr, ok := err.(*APIErrorDetails)
	if !ok {
		t.Fatalf("unexpected error type: %T", err)
	}
	if apiErr.StatusCode != http.StatusBadRequest || apiErr.RequestID != "req_123" {
		t.Fatalf("unexpected normalized error: %+v", apiErr)
	}
	if apiErr.Type != "invalid_request_error" || apiErr.Code != "resource_missing" {
		t.Fatalf("unexpected normalized fields: %+v", apiErr)
	}
}

func TestJSONLLoggerWritesFile(t *testing.T) {
	path := t.TempDir() + "/stripe.log"
	logger := NewJSONLLogger(path)
	logger.Log(map[string]any{"event": "request", "message": "ok"})
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read log: %v", err)
	}
	lines := strings.Split(strings.TrimSpace(string(data)), "\n")
	if len(lines) != 1 {
		t.Fatalf("expected one line, got %d", len(lines))
	}
	var decoded map[string]any
	if err := json.Unmarshal([]byte(lines[0]), &decoded); err != nil {
		t.Fatalf("decode json: %v", err)
	}
	if decoded["event"] != "request" {
		t.Fatalf("unexpected log event: %+v", decoded)
	}
	if _, ok := decoded["ts"]; !ok {
		t.Fatalf("expected ts field in log")
	}
}
