#!/usr/bin/env bash
set -euo pipefail

# Shared runtime defaults for automation agents.
# Override with env vars in workflows if needed.

export AGENT_LOG_ROOT="${AGENT_LOG_ROOT:-.artifacts/agent-logs}"
export AGENT_LOCK_ROOT="${AGENT_LOCK_ROOT:-.tmp/agent-locks}"
export AGENT_LOG_RETENTION_DAYS="${AGENT_LOG_RETENTION_DAYS:-14}"

export PR_GUARDIAN_RISK_MEDIUM_FILE_COUNT="${PR_GUARDIAN_RISK_MEDIUM_FILE_COUNT:-10}"
export PR_GUARDIAN_RISK_HIGH_FILE_COUNT="${PR_GUARDIAN_RISK_HIGH_FILE_COUNT:-25}"
export PR_GUARDIAN_MAX_AUTOFIX_FILES="${PR_GUARDIAN_MAX_AUTOFIX_FILES:-120}"

export WEBSITE_SENTRY_MAX_REMEDIATION_ATTEMPTS="${WEBSITE_SENTRY_MAX_REMEDIATION_ATTEMPTS:-2}"
export WEBSITE_SENTRY_RETRY_ATTEMPTS="${WEBSITE_SENTRY_RETRY_ATTEMPTS:-2}"
export WEBSITE_SENTRY_RETRY_DELAY_SECONDS="${WEBSITE_SENTRY_RETRY_DELAY_SECONDS:-3}"

export MARKET_RESEARCH_MAX_OPPORTUNITIES="${MARKET_RESEARCH_MAX_OPPORTUNITIES:-6}"
export MARKET_RESEARCH_MAX_NEW_TICKETS="${MARKET_RESEARCH_MAX_NEW_TICKETS:-3}"
export MARKET_RESEARCH_FEEDS="${MARKET_RESEARCH_FEEDS:-}"
